<?php

/**
 * implements hook_schema()
 */
 function my_database_install(){
	$schema['custom_table'] = array(
	'description'  =>  t('custom_table'),
	'fields'       =>  array(
	        'id'	 => array('type' => 'serial'),
			'number' => array('type' => 'int'),
			'teaser' => array('type' => 'varchar','length' => 150),
			'text'   => array('type' => 'text')
		),
	'primary key'=>array('id'),
	);
	return $schema;
 }